# Generated by Django 4.1.3 on 2023-01-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizacion', '0002_caracteristica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='optimizacion.producto'),
        ),
    ]
